# Generated by Django 3.2.25 on 2025-04-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_allorder_checkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorder',
            name='checkorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Checkorder', to='travello.checkorder'),
            preserve_default=False,
        ),
    ]
