# Generated by Django 3.2.25 on 2025-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_alter_allorder_checkorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
