# Generated by Django 3.2.25 on 2025-04-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
